"""add case and event log

Revision ID: 40389f230b26
Revises: 
Create Date: 2026-01-01 13:16:21.824667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40389f230b26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('initial_awareness_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'FOLLOW_UP', 'READY', 'SUBMITTED', 'CLOSED', name='casestatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_event_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('CASE_CREATED', 'INTAKE_RECEIVED', 'FIELD_SET', 'FIELD_CLEARED', 'NOTE_ADDED', 'AWARENESS_SET', 'AWARENESS_AMENDED', name='eventtype'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_type', sa.Enum('USER', 'SYSTEM', 'API', name='actortype'), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_event_log_case_id'), 'case_event_log', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_event_log_case_id'), table_name='case_event_log')
    op.drop_table('case_event_log')
    op.drop_table('cases')
    # ### end Alembic commands ###
